### ISSUE TITLE
ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by thongbn** [VirtusLab-Open-Source/strapi-plugin-navigation#290]
Hi team, i got this problem when using strapi 4.4.7 and 4.5.0, but do not now what is it. 
My db is: mariadb:10.7.3

UPDATE
  `navigations_localizations_links` as a,
  (
    SELECT `id`, ROW_NUMBER() OVER (PARTITION BY `navigation_id` ORDER BY `navigation_order`) AS src_order
    FROM `navigations_localizations_links`
    WHERE `navigation_id` = 1
  ) AS b
SET `navigation_order` = b.src_order
WHERE b.id = a.id - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction

**Comment by thongbn** [comment]
I think it got problem in i18n. Everytime i turn on i18n in navigation, add a language then navigate back to Navigation UI got deadlock, still happend in local.

**Comment by Th3vanger** [comment]
yes we have the same error

**Comment by cyp3rius** [comment]
Investigating

**Comment by LePulsar** [comment]
Same for me... Once I active i18n on the navigation parameters it breaks.

**Comment by thongbn** [comment]
Seem it is a bug in core of strapi, i've post a request here [,](https://github.com/strapi/strapi/issues/14937) . Waiting for new release

**Comment by petersg83** [comment]
Thank you! I could reproduce too!

**Comment by cyp3rius** [comment]
Holding investigation then :) Looking forward for fix in the next version of Strapi.

**Comment by thongbn** [comment]
I think problem is in Promise.all when parallel create or update navigation, according to this fix in strapi https://github.com/strapi/strapi/pull/15034
But in navigationSetupStrategy.js got parallel update too, so when waiting for strapi fix, i modified my navigation plug a little bit, still got lock some where but not crash hold strapi and able to use i18n. Hope this help. Basically, switch parallel to sequence create/update

In node_modules/strapi-plugin-navigation/server/i18n/navigationSetupStrategy.js. 
From Line 20 when 18nEnabled
`    if (config.i18nEnabled) {
        const hasNotAnyLocale = ({ localeCode }) => !localeCode;
        if (currentNavigations.length === 0) {
            currentNavigations = [
                await createDefaultI18nNavigation({ strapi, defaultLocale }),
            ];
        }
        if (currentNavigations.some(hasNotAnyLocale)) {
            const navs = [];
            for (const navigation of currentNavigations){
              navs.push(hasNotAnyLocale(navigation)
                ? await updateNavigation({
                  strapi,
                  current: navigation,
                  payload: {
                    localeCode: defaultLocale,
                  },
                  populate: utils_1.DEFAULT_POPULATE,
                })
                : navigation);
            }
            currentNavigations = navs;
            // currentNavigations = await Promise.all(currentNavigations.map(async (navigation) => {
            //     return hasNotAnyLocale(navigation)
            //         ? await updateNavigation({
            //             strapi,
            //             current: navigation,
            //             payload: {
            //                 localeCode: defaultLocale,
            //             },
            //             populate: utils_1.DEFAULT_POPULATE,
            //         })
            //         : navigation;
            // }));
        }
        const cnavs = [];
        const temps = currentNavigations
          .filter(({ localeCode }) => defaultLocale === localeCode);
        for (const rootNavigation of temps){
          const localizations = [
            ...(rootNavigation.localizations ?? []).map((localization) => (0, types_1.assertEntity)(localization, "Navigation")),
            rootNavigation,
          ];
          for (const locale of allLocale) {
            if (!localizations.some(({ localeCode }) => localeCode === locale)) {
              localizations.push(await createNavigation({
                strapi,
                payload: {
                  localeCode: locale,
                  slug: `${rootNavigation.slug}-${locale}`,
                  name: rootNavigation.name,
                  visible: true,
                },
              }));
            }
          }

          for(const current of localizations){
            updateNavigation({
              strapi,
              current,
              payload: {
                localizations: localizations.filter(({ id }) => id !== current.id),
              },
            })
          }
        }

        // await Promise.all(currentNavigations
        //     .filter(({ localeCode }) => defaultLocale === localeCode)
        //     .flatMap(async (rootNavigation) => {
        //     const localizations = [
        //         ...(rootNavigation.localizations ?? []).map((localization) => (0, types_1.assertEntity)(localization, "Navigation")),
        //         rootNavigation,
        //     ];
        //     for (const locale of allLocale) {
        //         if (!localizations.some(({ localeCode }) => localeCode === locale)) {
        //             localizations.push(await createNavigation({
        //                 strapi,
        //                 payload: {
        //                     localeCode: locale,
        //                     slug: `${rootNavigation.slug}-${locale}`,
        //                     name: rootNavigation.name,
        //                     visible: true,
        //                 },
        //             }));
        //         }
        //     }
        //     return await Promise.all(localizations.map((current) => updateNavigation({
        //         strapi,
        //         current,
        //         payload: {
        //             localizations: localizations.filter(({ id }) => id !== current.id),
        //         },
        //     })));
        // }));
    }
`

**Comment by cyp3rius** [comment]
The thing is @thongbn that now you're calling async actions in typical for condition so for sure it won't lock but also you can't be sure that all actions finished before you trigger next steps of plugin logic.

**Comment by thongbn** [comment]
Ya, i know it not a fix. but it not crash whole strapi for who still need i18n navigation in current project and use latest strapi version :( while wait strapi core release. I also apply fix in https://github.com/strapi/strapi/pull/15034 and patch-package plugin for build too

**Comment by petersg83** [comment]
I believe the issue is fixed now :)

**Comment by soapwong703** [comment]
@petersg83 I am still having this issue with i18n, can you please help?

``
[2023-03-06 18:43:27.883] error: insert into `navigations_localizations_links` (`inv_navigation_id`, `navigation_id`, `navigation_order`) values (17, 18, 1), (16, 18, 2) on duplicate key update `navigation_order` = values(`navigation_order`) - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
``

**Comment by petersg83** [comment]
Hello :) have you upgraded Strapi to the latest version?

I don't work at Strapi anymore so I won't be able to help more than that :)

**Comment by soapwong703** [comment]
My strapi version is v4.7.1 and it stills happen

**Comment by m7rlin** [comment]
same on v4.9.0

**Comment by mike85** [comment]
I just tried it with a fresh install of v4.9.0 but I get the error message all the time.

**Comment by m7rlin** [comment]
> I just tried it with a fresh install of v4.9.0 but I get the error message all the time.

Try this

i also have same message but when i do following steps it's gone

![image](https://user-images.githubusercontent.com/11756007/228968078-25374fc6-a78b-4a24-9ad1-cf658ae5518e.png)

Settings i18n to ENABLED, saving and restarting the server triggers the messages
![image](https://user-images.githubusercontent.com/11756007/228968258-742fb9ab-9874-4828-a280-a74bb1a08d89.png)

After that I shutdown the server and run:
1. Uninstalling strapi-plugin-navigation
```js
npm un strapi-plugin-navigation
```
2. Installing the plugin again
```js
npm i strapi-plugin-navigation
```
3. Remove build and .cache dir
4. Build and Develop
