### ISSUE TITLE
ER_LOCK_DEADLOCK error on Strapi start

### ISSUE THREAD

**Issue by sdgroot** [VirtusLab-Open-Source/strapi-plugin-navigation#347]
We're currently encountering a critical issue that prevents Strapi from starting at all, either with or without develop mode. We've enabled i18n in Strapi. This is the error that we're getting:
```
yarn run start
yarn run v1.22.19
$ strapi start
[2023-06-08 12:07:39.425] debug: ⛔️ Server wasn't able to start properly.
[2023-06-08 12:07:39.427] error: insert into `navigations_localizations_links` (`inv_navigation_id`, `navigation_id`, `navigation_order`) values (1, 2, 1), (3, 2, 2), (4, 2, 3), (5, 2, 4), (6, 2, 5) on duplicate key update `navigation_order` = values(`navigation_order`) - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
Error: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
    at Query.Sequence._packetToError (/strapi_path/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/strapi_path/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/strapi_path/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/strapi_path/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/strapi_path/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/strapi_path/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/strapi_path/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/strapi_path/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (/strapi_path/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/strapi_path/node_modules/mysql/lib/Connection.js:198:25)
    at /strapi_path/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/strapi_path/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/strapi_path/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/strapi_path/node_modules/knex/lib/client.js:146:12)
    at /strapi_path/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (/strapi_path/node_modules/knex/lib/execution/transaction.js:358:12)
error Command failed with exit code 1.
```

I'd also like to know why these queries are executed on Strapi startup in the first place? Is this something that the plugin does, or is this executed by Strapi? Even when all `navigations_` tables are empty there seems to be data inserted into these tables when Strapi starts.

**Additional info:**
strapi-plugin-navigation v2.2.9
Strapi v4.11.0 (also fails in v4.10.x)
MySQL v8.0.30
yarn v1.22.19
npm v9.7.1

**Comment by cyp3rius** [comment]
Investigating. But all operations are triggered by Strapi logic. Try to set plugin on the first place of `config/plugins.js` file like:

```js
{
   navigation: {
      enabled: true,
   },
   // ...
}
```

**Comment by cyp3rius** [comment]
#345

**Comment by loevstroem** [comment]
Any update on this?

**Comment by daan-ef2** [comment]
Yes, this is still an issue.

**Comment by loevstroem** [comment]
Incase anyone needs a temporary fix you can add "patch-package" and apply patch:

`--- a/node_modules/strapi-plugin-navigation/server/i18n/navigationSetupStrategy.js
+++ b/node_modules/strapi-plugin-navigation/server/i18n/navigationSetupStrategy.js
@@ -58,13 +58,15 @@ const i18nNavigationSetupStrategy = async ({ strapi, }) => {
                     }));
                 }
             }
-            return await Promise.all(localizations.map((current) => updateNavigation({
-                strapi,
-                current,
-                payload: {
-                    localizations: localizations.filter(({ id }) => id !== current.id),
-                },
-            })));
+            for (const current of localizations) {
+                await updateNavigation({
+                    strapi,
+                    current,
+                    payload: {
+                        localizations: localizations.filter(({ id }) => id !== current.id),
+                    },
+                })
+            }
         }));
     }
     else {
`

**Comment by cyp3rius** [comment]
@loevstroem may I ask you to create a PR with fix based on your snippet?

**Comment by daan-ef2** [comment]
There is more wrong at the navigationSetupStrategy. Its still trying to insert navigations that already exists other then the default locale. Trying to debug it now, thanks for pointing out the locaiton @loevstroem.

**Comment by loevstroem** [comment]
> @loevstroem may I ask you to create a PR with fix based on your snippet?

Absolutely.. Will submit later today.

**Comment by loevstroem** [comment]
> There is more wrong at the navigationSetupStrategy. Its still trying to insert navigations that already exists other then the default locale. Trying to debug it now, thanks for pointing out the locaiton @loevstroem.

It seems like a conditionrace in Strapi trying to insert the locales at the same time. The patch should fix it. If its the correct solution @cyp3rius should know 😄

**Comment by daan-ef2** [comment]
Tried your patch but it still fails at lline 64. If i add a condition in the CreateNavigation function, where i check if the slug already exists and update instead of creation it works. But its not the prettiest fix. If someone would help me beautify the code.

`const createNavigation = ({ strapi, payload, populate }) => {
 const exists = strapi.query("plugin::navigation.navigation").findOne({
    where: {
        slug: payload.slug,
      },
 })
if (!exists) {
   return strapi.query("plugin::navigation.navigation").create({
        data: {
          ...payload,
        },
        populate,
      });
}

return  strapi.query("plugin::navigation.navigation").update({
    data: {
      ...payload,
    },
    populate,
    where: {
      slug: payload.slug,
    },
  });
 
}`

**Comment by cyp3rius** [comment]
Maybe something like that? 

```
const createNavigation = async ({ strapi, payload, populate }) => {

  const where = {
    slug: payload.slug,
  };
  const data =  { ...payload };

  const exists = await strapi.query("plugin::navigation.navigation").findOne({ where  });
  if (!exists) {
     return strapi.query("plugin::navigation.navigation").create({
          data,
          populate,
        });
  }
return  strapi.query("plugin::navigation.navigation").update({
    data,
    populate,
    where,
  });
}
```

**Comment by cyp3rius** [comment]
Fixed in version `v2.2.15`

**Comment by daan-ef2** [comment]
Still got the error in 2.2.15 in an existing project with multiple multilingual menu's

```
Error: ER_DUP_ENTRY: Duplicate entry '31-30' for key 'navigations_localizations_links.navigations_localizations_links_unique'
    at Sequence._packetToError (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/knex/lib/client.js:146:12)
    at /Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at trxClient.query (/Users/daandegooijer/Projects/EF2@NEXT/leaseprof/back-end/node_modules/knex/lib/execution/transaction.js:358:12) {
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlMessage: "Duplicate entry '31-30' for key 'navigations_localizations_links.navigations_localizations_links_unique'",
  sqlState: '23000',
  index: 0,
  sql: 'alter table `navigations_localizations_links` add unique `navigations_localizations_links_unique`(`navigation_id`, `inv_navigation_id`)'
}
```
