### ISSUE TITLE
Strapi v5: Unable to delete navigation

### ISSUE THREAD

**Issue by michsko544** [VirtusLab-Open-Source/strapi-plugin-navigation#461]
Version: `3.0.0-beta.2`
Strapi: `5.0.5`

I got error 500 trying to delete the menu via the admin panel.

Steps to reproduce:

- go to the plugin tab
- click "Manage" button
- click trash button and confirm with "Delete" button

I had the same error when I tried to remove multiple menus simultaneously.

![Zrzut ekranu 2024-10-17 o 15 00 41](https://github.com/user-attachments/assets/e8bf27a7-3d42-4453-a747-d692576b61ac)

**Comment by cyp3rius** [comment]
Related with i18n issue. Should be fixed by the weekend.

**Comment by cyp3rius** [comment]
Issue was fixed in `v3.0.0-beta.3`

**Comment by michsko544** [comment]
Version: `3.0.0-beta.2`
Strapi: `5.1.0`

I still cannot delete the menu:

![Zrzut ekranu 2024-10-18 o 11 03 08](https://github.com/user-attachments/assets/505b48bb-f05c-4cda-a883-32cd675d2a9d)
![Zrzut ekranu 2024-10-18 o 11 05 27](https://github.com/user-attachments/assets/0ca54640-1f68-42e5-957e-c5ae2a782c22)
![Zrzut ekranu 2024-10-18 o 11 01 51](https://github.com/user-attachments/assets/2b467c15-4615-4e13-b056-30890d1ac934)

Do I need to reset something on db?

**Comment by cyp3rius** [comment]
Most probably you have got malformed leftovers in the database as `beta.3` introduce breaking change of how i18n is integrated.

If may I ask you to validate the behavior on empty database.

**Comment by michsko544** [comment]
@cyp3rius I have cleared the database and it seems that the problem still persists.
Strapi:
![Zrzut ekranu 2025-01-2 o 17 12 58](https://github.com/user-attachments/assets/33761a47-81bd-4e16-bca1-986415d3a910)

DB:
![Zrzut ekranu 2025-01-2 o 17 18 37](https://github.com/user-attachments/assets/c4eab0ac-3c57-42e3-9ffa-4952af989a21)

Version: `3.0.3`
Strapi: `5.6.0`

Steps to reproduce:
1. Setup clear database.
2. Start Strapi with `strapi develop`.
3. Create navigation.
4. Try to delete created navigation.

**Comment by cyp3rius** [comment]
Fix released in `v3.0.4`
