### ISSUE TITLE
Webhook not sending delete event

### ISSUE THREAD

**Issue by jsc-zyres** [VirtusLab-Open-Source/strapi-plugin-navigation#548]
We use a webhook to revalidate our frontend but receive no events when deleting navigation items.

![Image](https://github.com/user-attachments/assets/906076c3-887a-4ba4-92cc-c5d99a0e1d05)

Works for creating/updating navigation items and works for deleting other strapi components.

If you want to try it yourself just set up a simple endpoint that logs the request

Versions used

@strapi/strapi: 5.12.5
strapi-plugin-navigation: 3.0.11

Thanks in advance!

**Comment by cyp3rius** [comment]
Fix released in `3.0.13`

**Comment by jsc-zyres** [comment]
Thanks for the quick update.
Its nice that delete events are sent out now, but we still cant properly use this for revalidation since the information about the master of the deleted item is missing.
Would it be possible to include this information in the event as it is also done for create and update events?
